name: FastAPI CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ vars.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint
      run: |
        pip install flake8
        flake8 app/ tests/

    - name: Run unit tests
      run: |
        pip install pytest
        pytest tests/

    - name: Build Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/fastapi-app:latest .

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.DOCKERHUB_USERNAME }}/fastapi-app:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true

    - name: Log in to Docker Hub
      run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - name: Push image to Docker Hub
      run: |
        VERSION=1.0.${{ github.run_number }}
        docker tag $DOCKERHUB_USERNAME/fastapi-app:latest $DOCKERHUB_USERNAME/fastapi-app:$VERSION
        docker push $DOCKERHUB_USERNAME/fastapi-app:$VERSION
        docker push $DOCKERHUB_USERNAME/fastapi-app:latest
